server:
  port: 80

spring:
  devtools:
    livereload:
      port: 35730
  application:
    name: consumer-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率，1表示全部采集
      probability: 1

eureka:
  client:
    register-with-eureka: true
    # 单节点是否获取注册列表无所谓，集群下必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka