server:
  port: 9001

spring:
  application:
    name: provider-payment-service
  devtools:
    livereload:
      port: 35749
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
