server:
  port: 8401

spring:
  application:
    name: sentinel-service8401
  devtools:
    livereload:
      port: 35754
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8849
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-service8401
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
#      web-context-unify: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
