server:
  port: 9002

spring:
  application:
    name: provider-payment-service
  devtools:
    livereload:
      port: 35750
  cloud:
    nacos:
      discovery:
        # nacos集群
        # server-addr: 192.168.75.138:1111
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
